export const services = [
  {
    slug: 'branding',
    name: 'Branding',
    image: '/images/services/branding.webp',
    shortDescription: 'Visual identity, tone of voice, and positioning for authors and imprints.',
    overview: 'We build author and publisher identities that feel intentional, distinctive, and built to last. From visual identity systems to tone of voice, every element is designed around your work, your readership, and how you need to show up across different platforms.',
    process: [
      { step: 'Discovery & positioning', detail: 'We start by understanding you, your readership, your goals, and where your work sits in the market.' },
      { step: 'Identity design', detail: 'We develop the visual system, including logos, colour, typography, and supporting brand elements.' },
      { step: 'Voice & messaging', detail: 'Where required, we define the language and messaging that helps you talk about your work consistently.' },
      { step: 'Guidelines & handover', detail: 'Everything is brought together into a practical system you can continue using after the project ends.' },
    ],
    deliverables: ['Primary logo', 'Secondary logo', 'Submarks', 'Colour palette', 'Typography system', 'Brand guidelines', 'Social media templates', 'Media kit'],
    related: { label: 'Author Branding Essentials', kind: 'package', path: '/packages/author-branding-essentials' },
  },
  {
    slug: 'campaigns',
    name: 'Campaigns',
    image: '/images/services/campaigns.webp',
    shortDescription: 'Strategic launch and ongoing marketing campaigns built around your book and readership.',
    overview: 'We plan and create book marketing campaigns around what the project actually needs. That might mean launch strategy, creative direction, advertising, content, outreach, or a combination of channels working together.',
    process: [
      { step: 'Strategy & audience', detail: 'We establish the audience, objectives, timing, and channels that make sense for the campaign.' },
      { step: 'Creative direction', detail: 'We shape the campaign idea, messaging, and visual direction.' },
      { step: 'Campaign rollout', detail: 'We create and coordinate the agreed campaign activity across the relevant channels.' },
      { step: 'Review & refine', detail: 'We review performance throughout and adjust activity where useful.' },
    ],
    deliverables: ['Campaign strategy', 'Content planning', 'Creative assets', 'Advertising creative', 'Reporting & insights'],
  },
  {
    slug: 'social-media',
    name: 'Social media',
    image: '/images/services/social-media.webp',
    shortDescription: 'Content strategy and management built specifically around books, authors, and readers.',
    overview: 'Social media support designed around the way authors and publishing businesses actually work. We can build the strategy, create repeatable content systems, develop assets, or manage ongoing content depending on what you need.',
    process: [
      { step: 'Audit & strategy', detail: 'We look at your existing presence, audience, content, and goals before deciding what the channel needs to do.' },
      { step: 'Content direction', detail: 'We establish useful themes, formats, and recurring ideas that suit your voice and readership.' },
      { step: 'Creation & planning', detail: 'We develop the agreed content, assets, templates, and schedule.' },
      { step: 'Ongoing support', detail: 'For retained clients, we can continue managing, reviewing, and developing the content over time.' },
    ],
    deliverables: ['Content strategy', 'Content ideas', 'Post templates', 'Content calendar', 'Ongoing management options'],
    related: { label: 'Social Media Retainer', kind: 'package', path: '/packages/social-media-retainer' },
  },
  {
    slug: 'email-marketing',
    name: 'Email marketing',
    image: '/images/services/email-marketing.webp',
    shortDescription: 'Email strategy and systems that help turn readers into a lasting audience.',
    overview: 'We help authors and publishing businesses build email marketing that has a purpose beyond sending the occasional newsletter. That can include strategy, welcome journeys, launches, regular campaigns, templates, segmentation, and automation.',
    process: [
      { step: 'Review & strategy', detail: 'We look at your audience, current list, platform, and what email needs to achieve.' },
      { step: 'Journey planning', detail: 'We map useful subscriber journeys, campaigns, or automations.' },
      { step: 'Content & design', detail: 'We create the messaging and visual structure needed for the agreed emails.' },
      { step: 'Setup & handover', detail: 'We build the system and make sure you know how it works going forward.' },
    ],
    deliverables: ['Email strategy', 'Welcome sequences', 'Newsletter templates', 'Launch campaigns', 'Automation setup'],
  },
  {
    slug: 'book-covers',
    name: 'Book covers',
    image: '/images/services/book-covers.webp',
    shortDescription: 'Custom book cover design built around genre, readership, and the book itself.',
    overview: 'Custom cover design for independent authors and publishers. We look at the market your book sits within, how comparable titles are communicating with readers, and how to create something distinctive without losing the visual cues readers rely on.',
    process: [
      { step: 'Brief & research', detail: 'We start with the manuscript, positioning, genre, comparable titles, and practical format requirements.' },
      { step: 'Concept development', detail: 'We develop the strongest creative direction for the book.' },
      { step: 'Refinement', detail: 'The chosen direction is refined across typography, composition, imagery, and finish.' },
      { step: 'Final artwork', detail: 'We prepare the required files for ebook, print, and agreed promotional use.' },
    ],
    deliverables: ['Front cover', 'Full print cover', 'Ebook cover', 'Final production files'],
    related: { label: 'Premade covers', kind: 'shop', path: '/shop?category=premade_covers', customLabel: 'Commission a custom cover' },
  },
  {
    slug: 'websites',
    name: 'Websites',
    image: '/images/services/websites.webp',
    shortDescription: 'Custom websites for authors, publishers, and book businesses.',
    overview: 'We design and build websites around the needs of the person or business using them. That can be a focused author site, a publishing platform, an ecommerce site, or something more bespoke with its own content management and functionality.',
    process: [
      { step: 'Planning', detail: 'We establish what the site needs to do, who it is for, and how the content should be structured.' },
      { step: 'Design', detail: 'We develop the visual direction and page designs around your brand and content.' },
      { step: 'Build', detail: 'We build the agreed site and functionality, including content management where required.' },
      { step: 'Launch & handover', detail: 'We test, launch, and make sure you understand how to manage the site afterwards.' },
    ],
    deliverables: ['Custom design', 'Responsive build', 'Content management', 'SEO foundations', 'Launch support'],
  },
  {
    slug: 'editing-proofreading',
    name: 'Editing & proofreading',
    image: '/images/services/editing-proofreading.webp',
    shortDescription: 'Professional editorial support to help prepare your manuscript for publication.',
    overview: 'Editorial support for independent authors and publishing teams who want another experienced pair of eyes on the manuscript before publication. The exact level of intervention depends on the book and where you are in the process.',
    process: [
      { step: 'Manuscript review', detail: 'We establish the stage of the manuscript and the level of editorial support it needs.' },
      { step: 'Editorial work', detail: 'The agreed edit or proofread is completed directly against the manuscript.' },
      { step: 'Queries & corrections', detail: 'Comments, queries, and suggested corrections are clearly marked for review.' },
      { step: 'Final handover', detail: 'You receive the edited files ready for the next stage of production.' },
    ],
    deliverables: ['Copyediting', 'Proofreading', 'Editorial queries', 'Tracked changes', 'Clean final file where agreed'],
  },
  {
    slug: 'typesetting-layout',
    name: 'Typesetting & layout',
    image: '/images/services/typesetting-layout.webp',
    shortDescription: 'Professional interior design and typesetting for print and digital books.',
    overview: 'We turn the finished manuscript into a professionally designed book interior. The layout is developed around the format, genre, content, and reading experience, then prepared correctly for the platforms and printers you intend to use.',
    process: [
      { step: 'Format planning', detail: 'We establish trim size, formats, platform requirements, and the visual approach to the interior.' },
      { step: 'Interior design', detail: 'We create the typographic system, chapter styling, front matter, and other recurring elements.' },
      { step: 'Typesetting', detail: 'The complete manuscript is laid out and checked across the book.' },
      { step: 'Production files', detail: 'We prepare the final print and digital files required for publication.' },
    ],
    deliverables: ['Interior design', 'Print typesetting', 'Front and back matter layout', 'Print-ready PDF', 'Digital formatting where agreed'],
  },
  {
    slug: 'publishing-platform-support',
    name: 'Publishing & platform support',
    image: '/images/services/publishing-platform-support.webp',
    shortDescription: 'Practical publishing support for getting a finished book correctly set up and available for sale.',
    overview: 'Support for the practical work between having finished book files and actually publishing them. We can help with metadata, ISBNs, pricing, platform setup, distribution choices, upload requirements, and the details that are easy to miss when publishing independently.',
    process: [
      { step: 'Publishing plan', detail: 'We establish your formats, territories, distribution requirements, and publishing route.' },
      { step: 'Metadata & pricing', detail: 'We prepare the information your listings and distribution platforms need.' },
      { step: 'Platform setup', detail: 'We support setup across services such as Amazon KDP, IngramSpark, and Draft2Digital as required.' },
      { step: 'Publication checks', detail: 'We review the final setup so you know what is live, where it is available, and what still needs attention.' },
    ],
    deliverables: ['Metadata support', 'ISBN guidance', 'Pricing setup', 'Platform setup', 'Distribution guidance', 'Publication checks'],
  },
];

export const getServiceBySlug = (slug) => services.find((service) => service.slug === slug);
