export const services = [
  {
    slug: 'branding',
    name: 'Branding',
    image: '/images/services/branding.svg',
    shortDescription: 'Visual identity, tone of voice, and positioning for authors and imprints.',
    overview: "We build author and publisher identities that feel intentional, distinctive, and built to last. From visual identity systems to tone of voice, every element is designed to resonate with the right readers and hold up across every touchpoint from book covers to social media to press.",
    process: [
      { step: 'Discovery & positioning', detail: 'We start by understanding you, your readership, and where your work sits in the market.' },
      { step: 'Identity design', detail: 'We develop the visual system logos, colour, typography, and marks built around your voice.' },
      { step: 'Voice & messaging', detail: 'We define how you speak about your work, consistently and clearly.' },
      { step: 'Guidelines & handover', detail: 'Everything is packaged into clear guidelines and editable templates you can use straight away.' },
    ],
    deliverables: ['Primary logo', 'Secondary logo', 'Submarks', 'Colour palette', 'Typography system', 'Brand guidelines', 'Social media templates', 'Media kit'],
    related: { label: 'Author Branding Essentials', kind: 'package', path: '/packages' },
  },
  {
    slug: 'campaigns',
    name: 'Campaigns',
    image: '/images/services/campaigns.svg',
    shortDescription: 'Strategic launch and ongoing marketing campaigns that build momentum.',
    overview: "Strategic launch and sustained-visibility campaigns. We plan, create, and manage the marketing moments that give your book the attention it deserves before, during, and after publication. Each campaign is built around your readership, your goals, and the specific moment your book needs to land.",
    process: [
      { step: 'Strategy & audience', detail: 'We map your readers, your goals, and the channels that will actually move the needle.' },
      { step: 'Creative direction', detail: 'We shape the campaign concept, messaging, and the assets that carry it.' },
      { step: 'Channel rollout', detail: 'We plan and manage the rollout across social, email, ads, and PR as needed.' },
      { step: 'Review & refine', detail: 'We track what is working and adjust in real time to keep momentum.' },
    ],
    deliverables: ['Campaign strategy', 'Content calendar', 'Creative assets', 'Ad creative', 'Reporting & insights'],
  },
  {
    slug: 'social-media',
    name: 'Social media',
    image: '/images/services/social-media.svg',
    shortDescription: 'Content strategy and management built around your books and readership.',
    overview: "Content strategy and management tailored to publishing. We create systems that keep your presence consistent, your voice clear, and your audience growing without burnout so social media supports your writing life rather than competing with it.",
    process: [
      { step: 'Audit & strategy', detail: 'We review your current presence and define a clear, sustainable direction.' },
      { step: 'Content pillars', detail: 'We establish the themes and formats that give your feed structure and purpose.' },
      { step: 'Design & scheduling', detail: 'We design and schedule content that stays on-brand and on-time.' },
      { step: 'Engagement & growth', detail: 'We help you build genuine connection with your readers, not just numbers.' },
    ],
    deliverables: ['Content strategy', 'Post templates', 'Monthly content calendar', 'Community management guidance'],
    related: { label: 'Social Media Retainer', kind: 'package', path: '/packages' },
  },
  {
    slug: 'email-marketing',
    name: 'Email marketing',
    image: '/images/services/email-marketing.svg',
    shortDescription: 'Reader-focused email systems that convert attention into lasting engagement.',
    overview: "Reader-focused email strategy and execution. From welcome sequences to launch campaigns, we design systems that convert casual readers into committed ones and keep them engaged between books.",
    process: [
      { step: 'List & audience review', detail: 'We assess your list, your segments, and where the opportunities are.' },
      { step: 'Sequence design', detail: 'We map the journeys that turn subscribers into loyal readers.' },
      { step: 'Campaign creative', detail: 'We write and design the emails that carry your voice and your book.' },
      { step: 'Automation setup', detail: 'We set up the automations that keep things running without you.' },
    ],
    deliverables: ['Welcome sequence', 'Newsletter templates', 'Launch email campaign', 'Automation setup'],
  },
  {
    slug: 'book-covers',
    name: 'Book covers',
    image: '/images/services/book-covers.svg',
    shortDescription: 'Cover design that communicates genre, quality, and intent at a glance.',
    overview: "Cover design that works. We create covers that communicate genre, quality, and voice at first glance designed to perform in online retail thumbnails and in hand alike.",
    process: [
      { step: 'Brief & market research', detail: 'We study your genre, your comp titles, and your readers before designing.' },
      { step: 'Concept design', detail: 'We explore directions and land on a concept with the strongest market fit.' },
      { step: 'Refinement', detail: 'We refine typography, composition, and detail until it is right.' },
      { step: 'Final delivery', detail: 'You receive print-ready files, ebook covers, and social assets.' },
    ],
    deliverables: ['Front cover', 'Full print jacket', 'Ebook cover', 'Social media assets'],
    related: { label: 'Premade covers', kind: 'shop', path: '/shop?category=premade_covers', customLabel: 'Commission a custom cover' },
  },
  {
    slug: 'websites',
    name: 'Websites',
    image: '/images/services/websites.svg',
    shortDescription: 'Clean, purposeful author and publisher sites designed to support your work.',
    overview: "Clean, purposeful websites for authors and publishers. Designed to support your books, build your readership, and give your work a permanent, credible home online.",
    process: [
      { step: 'Strategy & sitemap', detail: 'We define what the site needs to do and how it should be structured.' },
      { step: 'Design', detail: 'We design a site that reflects your brand and serves your readers.' },
      { step: 'Build', detail: 'We build a fast, responsive site that is easy for you to maintain.' },
      { step: 'Launch & handover', detail: 'We launch, hand over, and show you how to keep it current.' },
    ],
    deliverables: ['Custom design', 'Responsive build', 'CMS setup', 'SEO foundation'],
  },
  {
    slug: 'publishing-support',
    name: 'Publishing support',
    image: '/images/services/publishing-support.svg',
    shortDescription: 'Publishing & production support — from manuscript to market-ready, wherever you publish.',
    overview: "Publishing & production support for authors and imprints handling their own release. We take care of the editorial, technical, and platform-side work that turns a finished manuscript into a properly published book — editing and proofreading, typesetting, metadata and pricing, platform setup across Amazon KDP, IngramSpark, Draft2Digital and others, plus ISBN management and rights consultation — so nothing gets missed between 'done writing' and 'live for sale'.",
    process: [
      { step: 'Manuscript assessment', detail: 'We review where your manuscript is and what it needs before it is ready for readers.' },
      { step: 'Editorial & production', detail: 'Structural editing, copyediting, proofreading, typesetting, and interior layout, handled to a professional standard.' },
      { step: 'Metadata & platform setup', detail: 'We set your pricing, metadata, and listings up correctly across Amazon KDP, IngramSpark, Draft2Digital and others, plus ISBN and rights.' },
      { step: 'Launch-ready handover', detail: 'You get a finished, correctly listed book and a clear record of what was done and where.' },
    ],
    deliverables: [
      'Editing & Proofreading',
      'Typesetting & Layout',
      'Platform & Rights Management',
    ],
  },
];

export const getServiceBySlug = (slug) => services.find((s) => s.slug === slug);
